Pass regex

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -58,5 +58,4 @@ jobs:
         run: |
           if [ -z "${{ steps.setup.outputs.version }}" ]; then exit 1; fi;
           if [ -z "${{ steps.setup.outputs.dry_run }}" ]; then exit 1; fi;
-          regex = '^([0-9]+)\.([0-9]+)\.([0-9]+).*?$'
-          if [[ "${{ steps.setup.outputs.version }}" =~ $regex ]]; then echo "Valid version"; else echo "INVALID VERSION FORMAT!";exit 1; fi;
+          if [[ "${{ steps.setup.outputs.version }}" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+).*?$ ]]; then echo "Valid version"; else echo "INVALID VERSION FORMAT!";exit 1; fi;
